# Generated by Django 2.2.3 on 2019-07-20 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20190720_1105'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Download',
            new_name='AppDownload',
        ),
    ]
