# Generated by Django 2.2.3 on 2019-07-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20190720_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdownload',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
    ]
