# Generated by Django 2.2.3 on 2019-07-23 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_appdownload_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
