# Generated by Django 2.2.3 on 2019-07-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_delete_greeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdownload',
            name='continent',
            field=models.CharField(default='', max_length=100),
        ),
    ]
